test_that("exported objects exist in namespace", {
  ns <- asNamespace("plsRcox")
  # Named exports
  expect_true(exists("DKplsRcox", envir = ns), info = "missing: DKplsRcox")
  expect_true(exists("DKplsRcoxmodel", envir = ns), info = "missing: DKplsRcoxmodel")
  expect_true(exists("DR_coxph", envir = ns), info = "missing: DR_coxph")
  expect_true(exists("coxDKpls2DR", envir = ns), info = "missing: coxDKpls2DR")
  expect_true(exists("coxDKplsDR", envir = ns), info = "missing: coxDKplsDR")
  expect_true(exists("coxDKsplsDR", envir = ns), info = "missing: coxDKsplsDR")
  expect_true(exists("coxpls", envir = ns), info = "missing: coxpls")
  expect_true(exists("coxpls2", envir = ns), info = "missing: coxpls2")
  expect_true(exists("coxpls2DR", envir = ns), info = "missing: coxpls2DR")
  expect_true(exists("coxpls3", envir = ns), info = "missing: coxpls3")
  expect_true(exists("coxpls3DR", envir = ns), info = "missing: coxpls3DR")
  expect_true(exists("coxplsDR", envir = ns), info = "missing: coxplsDR")
  expect_true(exists("coxsplsDR", envir = ns), info = "missing: coxsplsDR")
  expect_true(exists("cv.autoplsRcox", envir = ns), info = "missing: cv.autoplsRcox")
  expect_true(exists("cv.coxDKplsDR", envir = ns), info = "missing: cv.coxDKplsDR")
  expect_true(exists("cv.coxDKsplsDR", envir = ns), info = "missing: cv.coxDKsplsDR")
  expect_true(exists("cv.coxpls", envir = ns), info = "missing: cv.coxpls")
  expect_true(exists("cv.coxplsDR", envir = ns), info = "missing: cv.coxplsDR")
  expect_true(exists("cv.coxsplsDR", envir = ns), info = "missing: cv.coxsplsDR")
  expect_true(exists("cv.larsDR", envir = ns), info = "missing: cv.larsDR")
  expect_true(exists("cv.plsRcox", envir = ns), info = "missing: cv.plsRcox")
  expect_true(exists("larsDR_coxph", envir = ns), info = "missing: larsDR_coxph")
  expect_true(exists("plsRcox", envir = ns), info = "missing: plsRcox")
  expect_true(exists("plsRcoxmodel", envir = ns), info = "missing: plsRcoxmodel")

  # S3 methods (generic, class)
  expect_true(exists("DKplsRcoxmodel.default", envir = ns), info = "missing S3 method: DKplsRcoxmodel.default")
  expect_true(exists("DKplsRcoxmodel.formula", envir = ns), info = "missing S3 method: DKplsRcoxmodel.formula")
  expect_true(exists("coxDKpls2DR.default", envir = ns), info = "missing S3 method: coxDKpls2DR.default")
  expect_true(exists("coxDKpls2DR.formula", envir = ns), info = "missing S3 method: coxDKpls2DR.formula")
  expect_true(exists("coxDKplsDR.default", envir = ns), info = "missing S3 method: coxDKplsDR.default")
  expect_true(exists("coxDKplsDR.formula", envir = ns), info = "missing S3 method: coxDKplsDR.formula")
  expect_true(exists("coxDKsplsDR.default", envir = ns), info = "missing S3 method: coxDKsplsDR.default")
  expect_true(exists("coxDKsplsDR.formula", envir = ns), info = "missing S3 method: coxDKsplsDR.formula")
  expect_true(exists("coxpls.default", envir = ns), info = "missing S3 method: coxpls.default")
  expect_true(exists("coxpls.formula", envir = ns), info = "missing S3 method: coxpls.formula")
  expect_true(exists("coxpls2.default", envir = ns), info = "missing S3 method: coxpls2.default")
  expect_true(exists("coxpls2.formula", envir = ns), info = "missing S3 method: coxpls2.formula")
  expect_true(exists("coxpls2DR.default", envir = ns), info = "missing S3 method: coxpls2DR.default")
  expect_true(exists("coxpls2DR.formula", envir = ns), info = "missing S3 method: coxpls2DR.formula")
  expect_true(exists("coxpls3.default", envir = ns), info = "missing S3 method: coxpls3.default")
  expect_true(exists("coxpls3.formula", envir = ns), info = "missing S3 method: coxpls3.formula")
  expect_true(exists("coxpls3DR.default", envir = ns), info = "missing S3 method: coxpls3DR.default")
  expect_true(exists("coxpls3DR.formula", envir = ns), info = "missing S3 method: coxpls3DR.formula")
  expect_true(exists("coxplsDR.default", envir = ns), info = "missing S3 method: coxplsDR.default")
  expect_true(exists("coxplsDR.formula", envir = ns), info = "missing S3 method: coxplsDR.formula")
  expect_true(exists("coxsplsDR.default", envir = ns), info = "missing S3 method: coxsplsDR.default")
  expect_true(exists("coxsplsDR.formula", envir = ns), info = "missing S3 method: coxsplsDR.formula")
  expect_true(exists("larsDR_coxph.default", envir = ns), info = "missing S3 method: larsDR_coxph.default")
  expect_true(exists("larsDR_coxph.formula", envir = ns), info = "missing S3 method: larsDR_coxph.formula")
  expect_true(exists("plsRcoxmodel.default", envir = ns), info = "missing S3 method: plsRcoxmodel.default")
  expect_true(exists("plsRcoxmodel.formula", envir = ns), info = "missing S3 method: plsRcoxmodel.formula")
  expect_true(exists("predict.plsRcoxmodel", envir = ns), info = "missing S3 method: predict.plsRcoxmodel")
  expect_true(exists("print.plsRcoxmodel", envir = ns), info = "missing S3 method: print.plsRcoxmodel")
  expect_true(exists("print.summary.plsRcoxmodel", envir = ns), info = "missing S3 method: print.summary.plsRcoxmodel")
  expect_true(exists("summary.plsRcoxmodel", envir = ns), info = "missing S3 method: summary.plsRcoxmodel")
})
